image: "rust:latest"

variables:
  POSTGRES_DB: newsletter
  POSTGRES_PORT: 5432
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: password
  POSTGRES_HOST_AUTH_METHOD: trust

default:
  before_script:
    - rustc --version 
    - cargo --version
    - cargo install sqlx-cli --no-default-features --features postgres
    - chmod +x ./scripts/init_db.sh
    - SKIP_DOCKER=true ./scripts/init_db.sh

stages:
  - test

test-code:
  stage: test
  services:
    - postgres:12.2-alpine
  script:
    - cargo test
    - cargo install cargo-tarpaulin
    - cargo tarpaulin --ignore-tests

lint-code:
  stage: test
  script:
    - rustup component add clippy
    - cargo clippy -- -D warnings
    
format-code:
  stage: test
  script:
    - rustup component add rustfmt
    - cargo fmt -- --check

audit-code:
  stage: test
  services:
    - postgres:12.2-alpine
  variables:
    POSTGRES_DB: newsletter
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: password
    POSTGRES_HOST_AUTH_METHOD: trust
  script:
    - cargo install cargo-audit
    - cargo audit
