###
# Send a health_check - Should return 200 with no body
http://127.0.0.1:8000/health_check

###
# Health check for digital ocean
https://zero2prod-cfdxw.ondigitalocean.app/health_check

###

POST http://127.0.0.1:8000/subscriptions HTTP/1.1
content-type: application/x-www-form-urlencoded

name=le%20guin&email=ursula_le_guin%40gmail.com

###
# Health check for digital ocean
POST https://zero2prod-cfdxw.ondigitalocean.app/subscriptions HTTP/1.1
content-type: application/x-www-form-urlencoded

name=le%20guin&email=ursula_le_guin%40gmail.com