[package]
name = "zero2prod"
version = "0.1.0"
authors = ["damccull <damccull+git@gmail.com>"]
edition = "2018"

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "zero2prod"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "=4.0.0-beta.5"
actix-http = "=3.0.0-beta.5"
actix-service = "=2.0.0-beta.5"
serde = { version="1.0.126", features=["derive"] }
sqlx = { version="0.5.5", features=[
    "runtime-actix-rustls",
    "macros",
    "postgres",
    "uuid",
    "chrono",
    "migrate",
    "offline",
], default-features=false }
config = "0.11.0"
chrono = "0.4.19"
uuid = { version="0.8.2", features=["v4"] }
log = "0.4.14"
tracing = { version = "0.1.26", features = ["log"] }
tracing-futures = "0.2.5"
tracing-subscriber = { version = "0.2.19", features = ["registry", "env-filter"] }
tracing-bunyan-formatter = "0.2.4"
tracing-log = "0.1.2"
tracing-actix-web = "0.4.0-beta.4"


[dev-dependencies]
actix-rt = "2"
once_cell = "1.8.0"
reqwest = "0.11.3"
tokio = "1"
