[package]
name = "zero2prod"
version = "0.1.0"
authors = ["damccull <damccull+git@gmail.com>"]
edition = "2018"

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "zero2prod"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "=4.0.0-beta.5"
actix-http = "=3.0.0-beta.5"
actix-service = "=2.0.0-beta.5"
serde = { version = "1.0.126", features = ["derive"] }
sqlx = { version = "0.5.5", features = [
    "runtime-actix-rustls",
    "macros",
    "postgres",
    "uuid",
    "chrono",
    "migrate",
], default-features = false }
config = "0.11.0"
chrono = "0.4.19"
uuid = { version = "0.8.2", features = ["v4"] }


[dev-dependencies]
actix-rt = "2"
reqwest = "0.11.3"
tokio = "1"
