application:
  port: 8000
  host: "127.0.0.1"
database:
  host: "127.0.0.1"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "zero2prod"
email_client:
  base_url: "localhost"
  sender_email: "test@gmail.com"
  authorization_token: "set this in an environment variable"
